/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Database.gameScore;
import Engine.GameEngine;
import static GUI.Login.gamePlayer;
import java.awt.image.BufferedImage;
import static java.lang.Thread.sleep;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author dlweb
 */
public class Game extends javax.swing.JFrame {

    public static int score = 0;

    gameScore addscore;
    /**
     * Creates new form Game
     */
    GameEngine mathGame = null;
    BufferedImage gameOverview = null;
    static int milliSeconds = 0;
    static int Seconds = 0;
    static int minutes = 0;
    static int hours = 0;

    static boolean state = true;

    public Game() {
        initComponents();
        showgame(null);
        state = true;

        Thread clock = new Thread() {
            public void run() {
                for (;;) {
                    if (state == true) {
                        try {
                            sleep(1);

                            if (milliSeconds > 1000) {
                                milliSeconds = 0;
                                Seconds++;
                            }
                            if (Seconds > 60) {
                                milliSeconds = 0;
                                Seconds = 0;
                                minutes++;
                            }
                            if (minutes > 60) {
                                milliSeconds = 0;
                                Seconds = 0;
                                minutes = 0;
                                hours++;
                            }
                            milliSecond.setText(" : " + milliSeconds);
                            milliSeconds++;
                            Second.setText(" : " + Seconds);
                            minute.setText(" : " + minutes);
                            hour.setText(" : " + hours);
                        } catch (Exception e) {

                        }
                    } else {
                        break;
                    }
                }
            }
        };
        clock.start();
    }

    private void showgame(String gamer) {

        mathGame = new GameEngine(gamer);
        gameOverview = mathGame.nextGame();

        ImageIcon NextImage = new ImageIcon(gameOverview);
        textLable.setIcon(NextImage);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textNO = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        textLable = new javax.swing.JLabel();
        hour = new javax.swing.JLabel();
        minute = new javax.swing.JLabel();
        Second = new javax.swing.JLabel();
        milliSecond = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel1.setText("Enter The Number");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 590, -1, -1));

        textNO.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jPanel1.add(textNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 590, 70, 40));

        jButton1.setBackground(new java.awt.Color(0, 51, 153));
        jButton1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Submit");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 590, 86, 35));
        jPanel1.add(textLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 680, 400));

        hour.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        hour.setText("00 :");
        jPanel1.add(hour, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 50, 40));

        minute.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        minute.setText("00 :");
        jPanel1.add(minute, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 50, 40));

        Second.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Second.setText("00 :");
        jPanel1.add(Second, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 50, 40));

        milliSecond.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        milliSecond.setText("00 :");
        milliSecond.setToolTipText("");
        jPanel1.add(milliSecond, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 70, 40));

        jButton2.setText("Start");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("E:\\3 Year\\CIS\\Project_netBeams\\RatioMaths\\src\\main\\java\\resource\\bg_xl.jpg")); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 680));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int answer = Integer.parseInt(textNO.getText());
        boolean correct = mathGame.checkSolution(answer);
        int solution = mathGame.checkSolutionReturn();
        textNO.setText("");
        //int s = mathGame.getScore();
        //score = s;
        if (correct) {
            JOptionPane.showMessageDialog(this, "Correct Value");
            //gameOverview = mathGame.nextGame();
            //textScore.setText("" + s);
            score = score + 5;
            this.dispose();
            GameStatus push = new GameStatus();
            push.setVisible(true);
            ImageIcon NextImage = new ImageIcon(gameOverview);
            textLable.setIcon(NextImage);

        } else {
            JOptionPane.showMessageDialog(this, "Incorrect Value");
            state = false;
            addscore = new gameScore();
            addscore.addScore(gamePlayer, score);
            this.dispose();
            Score push = new Score();

            push.setVisible(
                    true);

        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        /*state = true;

        Thread clock = new Thread() {
            public void run() {
                for (;;) {
                    if (state == true) {
                        try {
                            sleep(1);
                            
                            if(milliSeconds > 1000){
                                milliSeconds = 0;
                                Seconds++;
                            }
                            if(Seconds > 60){
                                milliSeconds = 0;
                                Seconds = 0;
                                minutes++;
                            }
                            if(minutes > 60){
                                milliSeconds = 0;
                                Seconds = 0;
                                minutes = 0;
                                hours++;
                            }
                            milliSecond.setText(" : "+milliSeconds);
                            milliSeconds++;
                            Second.setText(" : "+Seconds);
                            minute.setText(" : "+minutes);
                            hour.setText(" : "+hours);
                        }
                        catch(Exception e)
                        {
                            
                        }
                    }
                    else
                    {
                        break;
                    }
                }
            }
        };
        clock.start();*/
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Second;
    private javax.swing.JLabel hour;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel milliSecond;
    private javax.swing.JLabel minute;
    private javax.swing.JLabel textLable;
    private javax.swing.JTextField textNO;
    // End of variables declaration//GEN-END:variables
}
